export const SHOW_FETCH_REQUESTED = 'SHOW_FETCH_REQUESTED';
export const SHOW_FETCH_SUCCEEDED = 'SHOW_FETCH_SUCCEEDED';
export const SHOW_FETCH_FAILED = 'SHOW_FETCH_FAILED';

export const EPISODE_FETCH_REQUESTED = 'EPISODE_FETCH_REQUESTED';
export const EPISODE_FETCH_SUCCEEDED = 'EPISODE_FETCH_SUCCEEDED';
export const EPISODE_FETCH_FAILED = 'EPISODE_FETCH_FAILED';
